---
- name: Check if kibana is installed
  command: dpkg-query -W kibana
  register: kibana_check_deb
  failed_when: kibana_check_deb.rc > 1
  changed_when: kibana_check_deb.rc == 1

- name: Download kibana-{{ kibana_version }}
  get_url:
    url="{{ kibana_url }}"
    dest="/var/kibana-{{ kibana_version }}.deb"
  when: kibana_check_deb.rc == 1 and kibana_url

- name: Copy kibana-{{ kibana_version }}
  copy:
    src="{{ kibana_local }}"
    dest="/var/kibana-{{ kibana_version }}.deb"
  when: kibana_check_deb.rc == 1 and kibana_local and not kibana_url

- name: Install kibana-{{ kibana_version }}
  apt: deb="/var/kibana-{{ kibana_version }}.deb"
  when: kibana_check_deb.rc == 1
  notify:
    - Start Kibana
  register: "kibana_installed"

# temporary evade issue https://github.com/ansible/ansible/issues/14270#issuecomment-416880078
- include: handlers/kibana_extra_folders.yml
  when: kibana_installed is defined and kibana_installed.changed == True

- name: Tweak kibana's service file for PID file permissions
  lineinfile:
    path: /etc/systemd/system/kibana.service
    insertafter: '^\[Service\]'
    line: 'RuntimeDirectory=kibana'

- name: Flush Handlers.
  meta: flush_handlers
