---
- name: Check if kibana is installed
  command: dpkg-query -W kibana
  register: kibana_check_deb
  failed_when: kibana_check_deb.rc > 1
  changed_when: kibana_check_deb.rc == 1

- name: Download kibana-{{ kibana_version }}
  get_url:
    url="{{ kibana_download }}"
    dest="/var/kibana-{{ kibana_version }}.deb"
  when: kibana_check_deb.rc == 1 and kibana_url

- name: Copy kibana-{{ kibana_version }}
  copy:
    src="{{ kibana_local }}"
    dest="/var/kibana-{{ kibana_version }}.deb"
  when: kibana_check_deb.rc == 1 and kibana_local and not kibana_url

- name: Install kibana-{{ kibana_version }}
  apt: deb="/var/kibana-{{ kibana_version }}.deb"
  when: kibana_check_deb.rc == 1
  notify:
    - Create Kibana extra folders
    - Start Kibana

- name: Tweak kibana's service file for PID file permissions
  lineinfile:
    path: /etc/systemd/system/kibana.service
    insertafter: '^\[Service\]'
    line: 'RuntimeDirectory=kibana'

- name: Flush Handlers.
  meta: flush_handlers
